### PR TITLE
start stop instance

### PR DESCRIPTION
**Pull request by fgimenez**
Towards https://github.com/giantswarm/giantswarm/issues/1886

CLI utility and library for spinning and setting up access to a remote minikube. This build uses it: https://circleci.com/gh/giantswarm/shipyard/17

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I am not into the bigger picture here. The PR is quite overwhelming for me because I miss all the details. I think it makes sense to use https://github.com/spf13/cobra for the CLI magic. When building CLI tools it would be cool to align the project structure with others. Maybe check https://github.com/giantswarm/opsctl. I am not sure my review is useful besides that.

**Comment by fgimenez** [comment]
> I think it makes sense to use https://github.com/spf13/cobra for the CLI magic

mmm i'm afraid of pulling too much deps, we are using just two flags atm, maybe when it gets a bit hairier? :)

**Comment by xh3b4sd** [comment]
> maybe when it gets a bit hairier? 

Roll how you prefer.

**Comment by fgimenez** [comment]
Thanks Tim!!

**Comment by fgimenez** [comment]
@xh3b4sd i think the better example now is https://github.com/giantswarm/shipyard/blob/master/pkg/shipyard/shipyard_test.go#L24, a shipyard instance is created and later used in https://github.com/giantswarm/shipyard/blob/master/pkg/shipyard/shipyard_test.go#L47, only the aws credentials environment variables are needed. Using it this way there's no need to change circle.yaml files and it integrates with architect, the tests are run as part of the existing suites.

Let me know if i can help setting it up.

**Comment by xh3b4sd** [comment]
This looks like I have to integrate it into my golang test which implies running all the AWS magic even when I am testing on my local laptop, where I have minikube already. Do I see this right? This is actually why I asked to a circle config and architect integration because I want to keep the local testing as easy as possible and when pushing to Github the AWS magic should be used automatically. I do not want to rewrite my go tests. That is not a nice integration IMO.

**Comment by fgimenez** [comment]
mmm using the same tests with both the local and the remote minikube without changing the tests can be challenging. I think that, with a small change in the tests, we could use both, just checking for env vars set in the CI https://circleci.com/docs/1.0/environment-variables/#basics in that case if they exists use the remote minikube, if not use the local one. This way architect and circle.yaml files stay the same.

I can include that code in shipyard too in order to make things easier.

**Pull request merged**
